//Initial
export const INITIALIZE = 'INITIALIZE'

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
export const TOGGLE_AUTH_POPUP = 'TOGGLE_AUTH_POPUP'

export const LOGGED_USER = 'LOGGED_USER'
export const LOG_OUT_USER = 'LOG_OUT_USER'
export const PASSED_LOGIN = 'PASSED_LOGIN'

export const GET_TAG = 'GET_TAG'
export const GET_QUOTES = 'GET_QUOTES'

export const TOGGLE_LIKE = 'TOGGLE_LIKE'
export const NEXT_QUOTE = 'NEXT_QUOTE'

export const ADMIN_QUOTES = 'ADMIN_QUOTES'
export const SET_ADMIN_QUOTES = 'SET_ADMIN_QUOTES'
export const EDIT_ADMIN_QUOTES = 'EDIT_ADMIN_QUOTES'
export const RESET_ADMIN_QUOTES = 'RESET_ADMIN_QUOTES'
export const UPDATE_QUOTE = 'UPDATE_QUOTE'
export const TOGGLE_DELETE_POPUP = 'TOGGLE_DELETE_POPUP'
export const DELETE_QUOTE = 'DELETE_QUOTE'
export const SET_ADMIN_FILTERS = "SET_ADMIN_FILTERS"
export const SET_CSV_DATA = "SET_CSV_DATA"
export const QUOTES_BULK_UPDATE = "QUOTES_BULK_UPDATE"

export const GET_ALL_TAGS = "GET_ALL_TAGS"
export const SET_LOCAL_TAGS = "SET_LOCAL_TAGS"
export const SEARCH_WITH_TAGS = "SEARCH_WITH_TAGS"
export const SET_TUTORIAL = "SET_TUTORIAL"
export const SET_LOADER = "SET_LOADER"
