//Initial
export const INITIALIZE = 'INITIALIZE'

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
export const TOGGLE_AUTH_POPUP = 'TOGGLE_AUTH_POPUP'

export const LOGGED_USER = 'LOGGED_USER'
export const LOG_OUT_USER = 'LOG_OUT_USER'

export const GET_TAG = 'GET_TAG'
export const GET_QUOTES = 'GET_QUOTES'

export const TOGGLE_LIKE = 'TOGGLE_LIKE'
export const NEXT_QUOTE = 'NEXT_QUOTE'

export const ADMIN_QUOTES = 'ADMIN_QUOTES'
export const SET_ADMIN_QUOTES = 'SET_ADMIN_QUOTES'
export const EDIT_ADMIN_QUOTES = 'EDIT_ADMIN_QUOTES'
export const RESET_ADMIN_QUOTES = 'RESET_ADMIN_QUOTES'
export const UPDATE_QUOTE = 'UPDATE_QUOTE'
